version: 2

models:
  - name: dim_address
    description: "Dimension d'adresses (nettoyage/normalisation depuis silver). Entrée basique générée automatiquement."

  - name: dim_type_local
    description: "Dimension des types de locaux (ex: Maison, Appartement). Entrée basique générée automatiquement."

  - name: fact_mutation
    description: "Fait principal des mutations/transactions immobilières. Entrée basique générée automatiquement."

  - name: stat_by_commune
    description: "Table de statistiques agrégées par commune. Entrée basique générée automatiquement."
