version: 2

models:
  - name: ban_addresses
    description: "Adresses issues du fichier BAN (données d'adresses). Entrée basique générée automatiquement."

  - name: dvf_silver
    description: "Transformation silver principale pour les données DVF (valeurs foncières). Entrée basique générée automatiquement."
