version: 2

sources:
  - name: bronze
    database: VALFONC_RAW
    schema: BRONZE
    description: |
      **Couche Bronze - Données brutes**
      
      Données sources non transformées, chargées depuis les fichiers sources.
    
    tables:
      - name: DVF_RAW_VARCHAR
        description: |
          Données brutes DVF (Demandes de Valeurs Foncières) avec toutes les colonnes en VARCHAR.
          Source originale avant toute transformation.
        
      - name: BAN_ADRESSES
        description: |
          **Base Adresse Nationale (BAN) - Données brutes**
          
          Référentiel national des adresses françaises.
          Contient les coordonnées géographiques (GPS + Lambert 93), les codes INSEE,
          et les informations cadastrales pour chaque adresse en France.
          
          Source : data.gouv.fr - Base Adresse Nationale
          Format : CSV consolidé national
          
          **Utilisation :**
          - Géocodage des adresses DVF
          - Enrichissement des coordonnées GPS
          - Validation des codes postaux et communes
          - Matching avec les parcelles cadastrales
        
        columns:
          - name: id
            description: Identifiant unique BAN de l'adresse
          
          - name: id_fantoir
            description: Identifiant FANTOIR de la voie (code national)
          
          - name: numero
            description: Numéro de voie
          
          - name: rep
            description: Indice de répétition (bis, ter, quater, etc.)
          
          - name: nom_voie
            description: Nom complet de la voie
          
          - name: code_postal
            description: Code postal (5 chiffres)
          
          - name: code_insee
            description: Code INSEE de la commune (5 chiffres)
          
          - name: nom_commune
            description: Nom officiel de la commune
          
          - name: code_insee_ancienne_commune
            description: Code INSEE de l'ancienne commune (avant fusion)
          
          - name: nom_ancienne_commune
            description: Nom de l'ancienne commune (avant fusion)
          
          - name: x
            description: Coordonnée X en projection Lambert 93 (mètres)
          
          - name: y
            description: Coordonnée Y en projection Lambert 93 (mètres)
          
          - name: lon
            description: Longitude en WGS84 (degrés décimaux)
          
          - name: lat
            description: Latitude en WGS84 (degrés décimaux)
          
          - name: type_position
            description: |
              Précision du positionnement géographique.
              Valeurs : housenumber, street, locality, municipality
          
          - name: alias
            description: Indicateur si l'adresse est un alias (0 ou 1)
          
          - name: nom_ld
            description: Nom du lieu-dit (si applicable)
          
          - name: libelle_acheminement
            description: Libellé d'acheminement postal
          
          - name: nom_afnor
            description: Nom de voie normalisé AFNOR
          
          - name: source_position
            description: Source des coordonnées géographiques
          
          - name: source_nom_voie
            description: Source du nom de voie
          
          - name: certification_commune
            description: Niveau de certification par la commune (0 ou 1)
          
          - name: cad_parcelles
            description: Liste des parcelles cadastrales associées
          
          - name: departement
            description: Code département (2 ou 3 chiffres)
