

SELECT
  HASH(COALESCE(UPPER(TRIM(TYPE_LOCAL)), 'INCONNU')) AS TYPE_LOCAL_ID,
  COALESCE(UPPER(TRIM(TYPE_LOCAL)), 'INCONNU') AS TYPE_LOCAL,
  CURRENT_TIMESTAMP() AS CREATED_AT,
  'DVF' AS SOURCE_SYSTEM
FROM {{ ref('stg_dvf_transactions') }}
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY COALESCE(UPPER(TRIM(TYPE_LOCAL)), 'INCONNU')
  ORDER BY TYPE_LOCAL
) = 1