WITH communes AS (
  SELECT
    UPPER(TRIM(COMMUNE)) AS COMMUNE_N,
    TRIM(CODE_POSTAL) AS CODE_POSTAL_N,
    TRIM(CODE_DEPARTEMENT) AS CODE_DEPARTEMENT_N
  FROM {{ ref('dim_address') }}
)
SELECT
  HASH(COMMUNE_N || '|' || CODE_DEPARTEMENT_N) AS COMMUNE_ID,
  COMMUNE_N AS COMMUNE,
  CODE_DEPARTEMENT_N AS CODE_DEPARTEMENT,
  CURRENT_TIMESTAMP() AS CREATED_AT
FROM communes
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY COMMUNE_N, CODE_DEPARTEMENT_N
  ORDER BY COMMUNE_N
) = 1